### ISSUE TITLE
No module named 'easydict'

### ISSUE THREAD

**Issue by VitaLemonTea1** [OpenGVLab/Instruct2Act#1]
Hi，I follow your "readme" and try to recurrent your program. But when I run the "robotic_anything_gpt_online_eval.py", it warn me that "No module named 'easydict'". So I write the issue and try to find your help.
Thanks!

**Comment by SiyuanHuang95** [comment]
Hi, thanks for your interest in this project.

For this issue, please use

"""
pip install easydict
"""

Bests

**Comment by VitaLemonTea1** [comment]
thanks!
