### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by nbbb24** [OpenGVLab/Instruct2Act#10]
Hi, thanks for your work

What if I just want to get the result after using SAM and Openclip, without performing any robot actions

Which files should i modify and run

Thanks!

**Comment by SiyuanHuang95** [comment]
Hi, thanks for your interest in our work!

If you just want to get the results after CLIP + SAM, you can check the functions *SAM()*, *CLIPRetrieval(objs, query)* in the [line](https://github.com/OpenGVLab/Instruct2Act/blob/bef8be75ff91de851cd203cdc2fb289bf22d54ec/engine_robotic.py#L449C5-L449C41). And the modify the main function do not execute the actions [HERE](https://github.com/OpenGVLab/Instruct2Act/blob/bef8be75ff91de851cd203cdc2fb289bf22d54ec/robotic_anything_offline.py#L203).

**Comment by nbbb24** [comment]
> 

Do i need to insert task in "visual_programm_prompt.py"?

**Comment by SiyuanHuang95** [comment]
The CLIP needs the parameter for objects query, like target object, you can insert it manually or let it done in visual_programm_prompt.py. It depends on your need.

The most simple why is just running the code, and delete the the action execution part.

**Comment by nbbb24** [comment]
> 

Alright, thank you so much!

**Comment by SiyuanHuang95** [comment]
Yep! Hope it helps.

I will close this issue currently. But you could re-open it whenever needed!
