### ISSUE TITLE
 Issue with GUI and Arm Movement

### ISSUE THREAD

**Issue by jk188jk** [OpenGVLab/Instruct2Act#11]
Hi,
After launching the GUI interface, I expected the robotic arm to move or provide some form of feedback. However, I am not observing any movement or receiving any prompts or error messages. 
Thank you for your time and support. 
![截图 2023-07-16 16-43-01](https://github.com/OpenGVLab/Instruct2Act/assets/86808138/7a0509ac-fa7d-41e2-ac3e-00138f9cf24b)

**Comment by SiyuanHuang95** [comment]
Hi,

can you have the following check:

1. Have you updated the Openai API key?
2. Do you enable the proxy if your network has some issues?
3. Have you prepared the ckpts for CLIP and SAM?

**Comment by jk188jk** [comment]
Yes, I have checked all these issues.

I'm just wondering what should be there when this GUI opens. Should there be a command interface for us to enter our prompts?

**Comment by SiyuanHuang95** [comment]
Hi, thanks for the update.

No, the prompt is extracted from the VIMA simulator.

Can you first try the offline version?

Or can you add some lines to print out the generated code lines to see what happens?

Bests,

**Comment by jk188jk** [comment]
This could be due to an incorrect version of CUDA on my system.

![截图 2023-07-17 20-22-14](https://github.com/OpenGVLab/Instruct2Act/assets/86808138/418ec1d7-66e9-4eb1-a05a-f4be3cd3bd8d)

**Comment by SiyuanHuang95** [comment]
Likely, yes. :-(

Would suggest that you first try something like torch.cuda.is_available(). 

The torch version I used is: torch==1.12.1+cu113. 

Hope it helps.

**Comment by SiyuanHuang95** [comment]
Since there is no further update, I will close this issue at first. But you could re-open it when you need. :-)
