### ISSUE TITLE
question about running the example

### ISSUE THREAD

**Issue by MisterBrookT** [OpenGVLab/Instruct2Act#12]
hi, thanks for your excellent work!

when i have installed all packages and run robotic_anything_gpt_online_eval.py, error happens:
![image](https://github.com/OpenGVLab/Instruct2Act/assets/132243877/3050c31e-811c-4c96-bf46-c8eda9184f70)
 I am a beginner in LLM and robotics, so i really don't know how to fix it , can you help me?

**Comment by SiyuanHuang95** [comment]
1. It's only SAM related part, we made some minor modifications to their source code.
2. You can follow the official one, and you just need to get the one make_generator.

**Comment by SiyuanHuang95** [comment]
Since there is no further update, I will close this issue.

You can open it when you need.
