### ISSUE TITLE
question about Rearrange task

### ISSUE THREAD

**Issue by FinnJob** [OpenGVLab/Instruct2Act#13]
Hi, thanks for your excellent work!
I wonder whether there is a rotation in the Rearrange task?
If yes, how do you calculate the degree? Thanks!

**Comment by SiyuanHuang95** [comment]
Hi, 

thanks for your interests in our project! 

We follow the default setting in VIMABench, where the success criteria is only concerning about the position information. 

You could insert some basic pattern matching function for the degree calculation if needed.

Bests

**Comment by FinnJob** [comment]
ok, thanks!
