### ISSUE TITLE
Did anyone run it successfully

### ISSUE THREAD

**Issue by zxb-0** [OpenGVLab/Instruct2Act#15]

**Comment by SiyuanHuang95** [comment]
Hi, maybe you can refer to the issue here to prepare: https://github.com/OpenGVLab/Instruct2Act/issues/6#issuecomment-1594038212

**Comment by yaofulan** [comment]
did you run it successfully? I encountered many problems

**Comment by SiyuanHuang95** [comment]
@yaofulan  you can open the new issues when you want
