### ISSUE TITLE
Do I need a paid plan for openAI?

### ISSUE THREAD

**Issue by ky0-999** [OpenGVLab/Instruct2Act#16]
Hi,
thanks for your excellent work.

I ckpts for CLIP and SAM prepared.
robotic_anything_gpt_online_eval.py 
is executed,

On the terminal
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.

Could you please tell me what the solution is?

**Comment by SiyuanHuang95** [comment]
Everyone has a 5-dollar quota as an initial. When you exceed this, you need to add a payment method to your account.
