### ISSUE TITLE
Unable to use other tasks in the code except drag and placed task

### ISSUE THREAD

**Issue by mana1003** [OpenGVLab/Instruct2Act#19]
![Error ](https://github.com/OpenGVLab/Instruct2Act/assets/123534133/a6794ac9-e7b0-4d18-89ea-492c70cd9d5f)

The OpenGL renderer open for the first task, completed it successfully. However all the subsequent task fail with the error shown above.

**Comment by SiyuanHuang95** [comment]
It seems to be related to the proxy? since the proxy or the internet takes too much time, and then the whole time exceeds the total time?
