### ISSUE TITLE
error occurred when I ran script "robotic_anything_gpt_online_eval.py"

### ISSUE THREAD

**Issue by yaofulan** [OpenGVLab/Instruct2Act#21]
(vima) csc@csclab:~/LLM$ /home/csc/anaconda3/envs/vima/bin/python /home/csc/LLM/Instruct2Act/robotic_anything_gpt_online_eval.py
pybullet build time: May 20 2022 19:45:31
[INFO] 17 tasks loaded
/home/csc/anaconda3/envs/vima/lib/python3.9/site-packages/scipy/__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Loading SAM...
Traceback (most recent call last):
  File "/home/csc/LLM/Instruct2Act/robotic_anything_gpt_online_eval.py", line 18, in <module>
    from engine_robotic import *
  File "/home/csc/LLM/Instruct2Act/engine_robotic.py", line 47, in <module>
    build_sam_func[sam_idx](
TypeError: build_sam_vit_h() got an unexpected keyword argument 'device'

do not know how to solve it.

**Comment by SiyuanHuang95** [comment]
you can remove the device argument, as I said in the README, it is only self-customization. 

The initial thing is just building the SAM encoder
