### ISSUE TITLE
No valid model configuration found

### ISSUE THREAD

**Issue by Keson1111** [OpenGVLab/Instruct2Act#24]
Hi,
When I try to read using the code tokenizer = open_clip.get_tokenizer("/data/openclip_tokenizer", direct_load=True), I have saved tokenizer.json under the path laion/CLIP-ViT-H-14-laion2B-s32B-b79K, but I cannot run it normally, showing an AssertionError: No valid model config found for /data/openclip_tokenizer. How can I solve this?

**Comment by SiyuanHuang95** [comment]
Hi, thanks for your interest.

You can refer to the issue here: https://github.com/mlfoundations/open_clip/issues/544#issuecomment-1611634906

For more following question, I am happy to have a further discussion! :-)
