### ISSUE TITLE
The problems about "Install the required packages with the provided environment.yaml"

### ISSUE THREAD

**Issue by wwwzxxzw** [OpenGVLab/Instruct2Act#26]
Hello! Your work is excellent. I would like to reproduce this paper, but I encountered the problems as shown in the figures. Specifically, I tried to install packages by running the command conda env create -f environment.yaml, but encountered an error. Currently, I am unsure how to resolve this issue. Could you please offer some assistance? Thank you very much!
![1726060683554](https://github.com/user-attachments/assets/59048e69-4b63-4e95-8a9b-940f63c0bf19)
![1726060752161](https://github.com/user-attachments/assets/f4c43a0d-4175-4625-a942-e36d75360750)

**Comment by wwwzxxzw** [comment]
VMware ubuntu20.04

**Comment by SiyuanHuang95** [comment]
You can extract the package info from the yaml, and adapt it to your local machine.

Also, we do not have knowledge of the VM machine.
