### ISSUE TITLE
Pretrained weights not found for model ViT-H-14.

### ISSUE THREAD

**Issue by VitaLemonTea1** [OpenGVLab/Instruct2Act#4]
Hi!

There is another question. When I run the robotic_anything_gpt_online_eval.py ,it fails with Pretrained weights not found for model ViT-H-14. How can I get this file?

Thanks!

**Comment by SiyuanHuang95** [comment]
Hi,

I guess you need to download the ckpts from: https://github.com/mlfoundations/open_clip
