### ISSUE TITLE
How can I make the robotic arm move

### ISSUE THREAD

**Issue by VitaLemonTea1** [OpenGVLab/Instruct2Act#7]
Hi,

I successfully run the visual window of Vimabench. But I dont know how to make it move after I read the "readme". Could you please give me any suggestions.

Thanks

**Comment by SiyuanHuang95** [comment]
If you are in the mainland of China and using the OpenAI api, you need to deal with the proxy issue.

How about starting with the offline trial?

**Comment by VitaLemonTea1** [comment]
Thanks for your reply!


I would try your way tomorrow.



---Original---
From: "Siyuan ***@***.***&gt;
Date: Thu, Jun 22, 2023 01:13 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [OpenGVLab/Instruct2Act] How can I make the robotic arm move(Issue #7)




 
If you are in the mainland of China and using the OpenAI api, you need to deal with the proxy issue.
 
How about starting with the offline trial?

**Comment by SiyuanHuang95** [comment]
Okay. Just try it, and see whether it works! :-)
