### ISSUE TITLE
Can I get the success rate form of offline mode

### ISSUE THREAD

**Issue by VitaLemonTea1** [OpenGVLab/Instruct2Act#8]
Hi，

I run the offline mode these days. Can I get the success rate form of offline mode to compare with my result.

Thanks!

**Comment by SiyuanHuang95** [comment]
Hi, 

thanks for your interest in this project.

Actually, we did not calculate the SR of offline mode. But you can calculate the SR with our provided script. For the structured tasks in VIMA, I guess the results would be similar to the online version.

**Comment by SiyuanHuang95** [comment]
Since no further update, I will close this issue.
